# Generated by Django 4.2.3 on 2023-08-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
